apiVersion: apps/v1
kind: Deployment
metadata:
  name: OurMemoryApp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: OurMemoryApp
  template:
    metadata:
      labels:
        app: OurMemoryApp
    spec:
      containers:
      - name: OurMemoryApp
        image: sergionguyen12397/OurMemoryApp
        ports:
        - containerPort: 80